---

- name: Provision macOS applications used for development
  hosts: localhost

  roles:
    - { role: ssh, tags: ssh }
    - { role: git, tags: git }
    #- { role: visual_studio_code, tags: visual_studio_code }
    - { role: awscli, tags: awscli }
    - { role: ricty, tags: ricty }
    #- { role: powerline-fonts, tags: powerline-fonts }
    - { role: java, tags: java }
    - { role: golang, tags: golang }
    - { role: node, tags: node }
    - { role: docker, tags: docker }
    - { role: mas, tags: mas }

- import_playbook: tasks/install-development.yml
