---
# file: roles/awscli/tasks/main.yml

- name: Tap homebrew repositories
  homebrew_tap: name={{ item }}
  with_items:
    - youyo/awslogin

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items:
    - awscli
    - awslogin

- name: Ensure {{ ansible_user_dir }}/.aws directory exists
  file:
    path: "{{ ansible_user_dir }}/.aws"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

