---
# file: roles/python/tasks/main.yml

- name: Install python
  homebrew: name={{ item }}
  with_items:
    - pyenv

- name: Install config in global fish configuration
  copy:
    src: "{{ role_path }}/files/fishconf.d/"
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
