---
# file: roles/mas/tasks/main.yml

- name: Install homebrew packages - mas
  homebrew: name=mas

- name: MAS | get installed list
  shell: mas list
  register: mas_installed_list
  changed_when: False
  check_mode: no

- name: MAS | install items
  shell: "mas install {{ item.id }}"
  when: 'item.id|string not in mas_installed_list.stdout'
  with_items:
    - { id: 409183694, name: Keynote }
    - { id: 409201541, name: Pages }
    - { id: 409203825, name: Numbers }
    - { id: 557168941, name: Tweetbot }
    - { id: 411643860, name: DaisyDisk }
    # - { id: 1295203466, name: Microsoft Remote Desktop 10 }

# - LINE
