---
# file: roles/git/tasks/main.yml

- name: Tap homebrew repositories
  homebrew_tap: name={{ item }}
  with_items:
    - kyoshidajp/tosa

- name: Remove homebrew packages
  homebrew: name={{ item }} state=absent
  with_items:
    - git-flow

- name: Install homebrew packages - git
  homebrew: name={{ item }}
  with_items:
    - git
    - hub
    - git-flow-avh
    - git-secrets
    - tosa

- name: Ensure .config/git directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Install ignore in global git configuration
  copy:
    src: ignore
    dest: "{{ ansible_user_dir }}/.config/git/ignore"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644


- name: Install config in global git configuration
  copy:
    src: config
    dest: "{{ ansible_user_dir }}/.config/git/config"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
