---

- name: Tap homebrew caskroom versions repositories
  homebrew_tap: name=caskroom/versions

- name: Install JDKs
  homebrew_cask: name={{ item }}
  with_items:
    - java # oracle java 10
    - java9 # oracle java 9
    - java8 # oracle java 8

- name: Add JDKs
  shell: jenv add $(/usr/libexec/java_home -v {{ item }})
  args:
    creates: "{{ anyenv_install_path }}/envs/jenv/versions/{{ item }}/bin/java"
  with_items:
    - "10.0"
    # - "1.9"
    - "1.8"

- name: Add java-related packages
  homebrew: name={{ item }}
  with_items:
    - gradle
    - maven

# - name: Install JVM languages
#   homebrew: name={{ item }}
#   with_items:
#     - scala

- name: Add jenv plugins
  shell: eval "$(jenv init -)" && jenv enable-plugin {{ item }}
  register: result
  changed_when: '"plugin already enabled" not in result.stdout'
  with_items:
    - maven
    - gradle
    - groovy
