- name: Install anyenv
  git:
    repo: "{{ anyenv_git_url }}"
    dest: "{{ anyenv_install_path }}"

- name: Configure anyenv
  template:
    src: anyenv.rc.j2
    dest: "{{ zsh_custom_dir }}/anyenv.zsh"

# - name: Create envs direcrory
#   file:
#     path: "{{anyenv_install_path}}/envs"
#     state: directory

- name: Remove __env in brew
  homebrew: name={{item}} state=absent install_options=force
  with_items: "{{ envs }}"

- name: Remove __env directory
  file: path="~/.{{item}}" state=absent
  with_items: "{{ envs }}"

- name: Remove nodebrew
  homebrew: name=nodebrew state=absent install_options=force

- name: Remove .nodebrew directory
  file: path="~/.nodebrew" state=absent

- name: Install envs
  shell: >
    eval "$(anyenv init -)";
    anyenv install {{ item }}
  args:
    creates: "{{ anyenv_install_path }}/envs/{{item}}"
  environment:
    PATH: "{{ anyenv_install_dir }}/bin:{{ lookup('env', 'PATH') }}"
  with_items: "{{ envs }}"

- include_tasks: java.yml
# - include_tasks: go.yml
# - include_tasks: python.yml
# - include_tasks: node.yml
# - include_tasks: ruby.yml
